#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_MOMENTARY

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY

// #define PLOOPY_DPI_OPTIONS { 4800 }
// #define PLOOPY_DPI_DEFAULT 0

// #undef PLOOPY_DRAGSCROLL_DIVISOR_H
// #define PLOOPY_DRAGSCROLL_DIVISOR_H 16.0
// #undef PLOOPY_DRAGSCROLL_DIVISOR_V
// #define PLOOPY_DRAGSCROLL_DIVISOR_V 16.0